using System;
using System.Collections.Generic;
using System.Text;

namespace NotEnoughMadness.MapMaking
{
    [Serializable]
    public enum NEM_SkillsList
    {
        ___________________CORE___________________,
        Unarmed1 = 10,
        Unarmed2,
        Unarmed3,
        Melee1 = 20,
        Melee2,
        Melee3,
        Ranged1 = 30,
        Ranged2,
        Ranged3,
        Acrobatic1 = 40,
        Acrobatic2,
        Acrobatic3,
        ___________________UNARMED___________________,
        LightPunch = 220,
        CritPunch,
        SpecialStrike,
        UNUSED1,
        ImprovWeapon,
        FocusPunch,
        BetterSpecialStrike,
        StunningFist,
        CritPunchBonus,
        PowerFinish,
        ExposeCover,
        Revelator,
        MegaFinish,
        Footwork = 240,
        XXX_REMOVED2,
        Ablation,
        Counter,
        XXX_REMOVED_Grapple,
        XXX_REMOVED3,
        DashAttack,
        DashHeavyAttack,
        PunchEnerv,
        MeleeCounter,
        XXX_REMOVED4,
        BasicGuard = 260,
        BetterGuard,
        GuardAiming,
        XXX_REMOVED5,
        XXX_REMOVED6,
        AdvancedGuard,
        XXX_REMOVED7,
        Reciprocate,
        GuardMobility,
        CounterCharging,
        MeleeGuard,
        AdvancedGuardMobility,
        ___________________MELEE___________________,
        LightSwing = 420,
        UNUSED2,
        CritSwing,
        XXX_REMOVED9,
        BluntKnockback,
        FocusSwing,
        FollowThrough,
        CritSwingBonus,
        XXX_REMOVED10,
        XXX_REMOVED_11,
        BigWeapons,
        BlockBreaker,
        REMOVED_CarryOver,
        Positioning = 440,
        EdgedTiming,
        MinorLeague,
        XXX_REMOVED,
        XXX_REMOVED_12,
        DualMelee,
        EdgedSpeed,
        XXX_REMOVED_13,
        AdvancedDualMelee,
        QuickUnsheath,
        ZipAttack,
        XXX_REMOVED_14,
        BasicBlock = 460,
        BetterBlock,
        BlockAiming,
        BlockMobility,
        Riposte,
        Parry,
        AdvancedBlock,
        BlockBullets,
        DeflectBullets,
        ReflectBullets,
        XXX_REMOVED_15,
        AdvancedBlockMobility,
        ___________________RANGED___________________,
        StationaryRecovery = 620,
        Unphased,
        DirectionTracking,
        CoverBracing,
        AutoFireComp,
        Quickdraw,
        Highground,
        Unwavering,
        MobileAcc,
        HeavyArms,
        AutoFireCorrect,
        PerfectSights,
        Headshot = 640,
        GreatShot,
        Unobstructed,
        DualRanged,
        PistolWhip,
        ZeroTolerance,
        DisarmingShot,
        MagicBullet,
        ShotgunBlastoff,
        AdvancedDualRanged,
        XXX_REMOVED_27,
        OffHandAim = 660,
        SweetSpot,
        AimAssist,
        XXX_REMOVED_16,
        XXX_REMOVED_17,
        XXX_REMOVED_18,
        CriticalShot,
        XXX_REMOVED_19,
        MobileAim,
        XXX_REMOVED_20,
        XXX_REMOVED_21,
        PrecisionShooter,
        PinDown,
        Deadeye,
        ___________________ACROBAT___________________,
        TacticalNovice = 820,
        MovingTarget,
        TacticalJourneyman,
        DodgeTackle,
        SnapDodge,
        ShootDodge,
        PickupKick,
        PickupLeaping,
        TacticalMaster,
        HeadLeap,
        SprintFire,
        XXX_REMOVED_22,
        XXX_REMOVED_135 = 840,
        PreciseThrow,
        CatchThrown,
        ShurikenThrow,
        MadarangDisarm,
        DeadlyThrow,
        XXX_REMOVED_Boomerang,
        XXX_REMOVED_23,
        ShurikenArc,
        LethalBluntThrow,
        Lawnmower,
        ThrowBig,
        AthleticSprint = 860,
        XXX_REMOVED_24,
        FastGetup,
        XXX_REMOVED_333,
        XXX_REMOVED_222,
        Plummet,
        TimedKipUp,
        FallTumble,
        TacSprint,
        XXX_REMOVED_25,
        XXX_REMOVED_26,
        FallRoll,
        ___________________ORIGIN___________________,
        Tinkerer = 1000,
        Scary,
        BribeEnemy,
        ImaginaryFriend,
        Infiltrator,
        FreeExecute,
        Hungry,
        Sturdy,
        Vanisher,
        Throwmaster,
        Corruption,
        Arcane,
        Operative,
        Replicate,
        ___________________END___________________ = 99999
    }
}
